### ISSUE TITLE
Unexpected :error_no_members

### ISSUE THREAD

**Issue by djthread** [epgsql/pooler#54]
Hello, Seth!

I'm using pooler in my Elixir app to connect to my favorite music player service (MPD). I'm a bit confused with the behavior I'm seeing from pooler, though. With my config, I do see 2 ExMpd.Connection processes spawn to start. But when both are in use and I request a third, instead of creating a new one and ramping up toward 5 as I expected, I notice that the pooler:take_group_member(:mpd) call is returning :error_no_members.

Surely I'm just missing something simple, but I'm not sure what it is! The readme says that new workers should be spawned "on demand" ... but I would have thought calling take_group_member would qualify.

```
config :pooler, pools: [
  [
    name:       :mpd,
    group:      :mpd,
    init_count: 2,
    max_count:  5,
    start_mfa:  {ExMpd.Connection, :start_link, [mpd_host, mpd_port]}
  ]
]
```

Thanks in advance for any thoughts!

Adam

**Comment by MaxPower15** [comment]
+1 I believe this issue is causing weird behavior with the riak elixir client, referenced above. It would be good to know if this behavior is intentional or not so libs can either deal with it or wait for a fix.

**Comment by hansonkd** [comment]
I would like to add, that I get this behavior only when trying to set it as a variable:

<img width="414" alt="screen shot 2016-02-21 at 5 26 59 pm" src="https://cloud.githubusercontent.com/assets/496914/13207200/70784e70-d8c0-11e5-8158-8c9128fcdc42.png">

**Comment by sdelano** [comment]
We've run into this issue as well and have tracked it down where it happens in the source w/in `pooler.erl`. It appears that this behavior is intentional, but the reasoning is still misunderstood.

Here's the code: https://github.com/seth/pooler/blob/a145451a2f12673b4f55c4657e1b572fc5dc4b8a/src/pooler.erl#L573-L585

If you're at the limit, you'll automatically get an `error_no_members` return while pooler asynchronously adds new workers.

@hansonkd - for what you're seeing, you've most likely set your init count to 1 and you're growing by 1 worker every time you get an `error_no_members` return. It just so happens that you're alternating calls that assign variables and then don't.

**Comment by sata** [comment]
Any reason for not using take_member/2 with a timeout? A low figure timeout which would let the gen_server perform the batch add of new member before responding back to the caller.

Essentially you would be stating that the max allowed time for the caller to be stalled would be the timeout value. take_member/1 has 0 as timeout. 

@seth: I'm curious about the design choice here. Any particular use case of take_member/1 with 0 timeout when culling free members is of interest, that is, having different init and max values?

**Comment by seth** [comment]
First off, very sorry for the delayed responses. It's awesome to see pooler getting continued and on-going use! 

In pooler's initial design, I avoided queuing and chose to have the pool return immediately with an error when no members are available. This met my needs at the time and kept the implementation simple. While errors aren't always nice, avoiding high latency variance sure is.

The dynamic pool re-sizing was added before the queuing feature (to my memory, didn't go look at git). So the choice to return an error during resize was made on purpose because it followed the original design and keeps things simple -- but not all work loads will be happy with this "fail first" approach.

With the queuing feature in place, no reason not to use it if that is the behavior you're looking for. I'd gladly take a patch to allow timeout to be specified for take_group_member.

**Comment by cjimison** [comment]
I just added a pull request for this encase others run into it :P

**Comment by seriyps** [comment]
As Seth mentioned, this behaviour is intentional. `take_member(Pool)` is equivalent to `take_member(Pool, 0)` (i.e. 0 timeout), so even though the new worker is spawned on background, the current requestor will get `error_no_members`.

And if someone wants to get a worker back no matter what, they need to use `take_member` with some reasonable timeout. As I understand, `take_member/2` was not implemented, when this ticket was created, so, I'm closing it.
